# LSTM vs GRU Comparison for Sentiment Analysis

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dense
from sklearn.model_selection import train_test_split

In [7]:
texts = [
    "I love deep learning",
    "Artificial intelligence is amazing",
    "This course is excellent",
    "I am very happy today",
    "The movie was fantastic",
    "I hate this product",
    "This is very bad",
    "The service was terrible",
    "I am disappointed",
    "The experience was awful"
]

labels = [1,1,1,1,1,0,0,0,0,0]

In [8]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
max_length = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen = max_length)
y = np.array(labels)
print("X = ", X)
print("y = ", y)

X =  [[ 0  1  8  9 10]
 [ 0 11 12  2 13]
 [ 0  3 14  2 15]
 [ 1  6  7 16 17]
 [ 0  4 18  5 19]
 [ 0  1 20  3 21]
 [ 0  3  2  7 22]
 [ 0  4 23  5 24]
 [ 0  0  1  6 25]
 [ 0  4 26  5 27]]
y =  [1 1 1 1 1 0 0 0 0 0]


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

## LSTM Model

In [20]:
lstm_model = Sequential([
    Embedding(
        input_dim = len(tokenizer.word_index) + 1,
        output_dim = 16,
        input_length=max_length
    ),
    LSTM(64),
    Dense(1, activation='sigmoid')
])

C:\Users\rakes\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
lstm_model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)
lstm_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
history_lstm = lstm_model.fit(
    X_train,
    y_train,
    epochs = 20,
    validation_data = (X_test, y_test),
    verbose = 1
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3750 - loss: 0.6935 - val_accuracy: 0.5000 - val_loss: 0.6920
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6927 - val_accuracy: 1.0000 - val_loss: 0.6924
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.6918 - val_accuracy: 0.5000 - val_loss: 0.6929
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7500 - loss: 0.6909 - val_accuracy: 0.0000e+00 - val_loss: 0.6935
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7500 - loss: 0.6900 - val_accuracy: 0.0000e+00 - val_loss: 0.6940
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.6890 - val_accuracy: 0.0000e+00 - val_loss: 0.6946
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.6879 - val_accuracy: 0.0000e+00 - val_loss: 0.6953
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.6867 - val_accuracy: 0.0000e+00 -

In [23]:
lstm_loss, lstm_accuracy = lstm_model.evaluate(
    X_test,
    y_test,
    verbose = 0
)

print(f"LSTM Loss: {lstm_loss:.4f}")
print(f"LSTM Accuracy : {lstm_accuracy:.4f}")

LSTM Loss: 0.7136
LSTM Accuracy : 0.0000


## GRU Model

In [24]:
gru_model = Sequential([
    Embedding(
        input_dim = len(tokenizer.word_index) + 1,
        output_dim = 16,
        input_length = max_length
    ),
    GRU(32),
    Dense(1, activation = 'sigmoid')
])

In [25]:
gru_model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)
gru_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
history_gru = gru_model.fit(
    X_train,
    y_train,
    epochs = 20,
    validation_data = (X_test, y_test),
    verbose = 1
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3750 - loss: 0.6937 - val_accuracy: 0.5000 - val_loss: 0.6917
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6250 - loss: 0.6924 - val_accuracy: 0.5000 - val_loss: 0.6922
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6250 - loss: 0.6911 - val_accuracy: 0.5000 - val_loss: 0.6928
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.6897 - val_accuracy: 0.5000 - val_loss: 0.6934
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.6884 - val_accuracy: 0.5000 - val_loss: 0.6939
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.6870 - val_accuracy: 0.0000e+00 - val_loss: 0.6946
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8750 - loss: 0.6856 - val_accuracy: 0.0000e+00 - val_loss: 0.6952
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.6842 - val_accuracy: 0.0000e+00 - val_lo

In [27]:
gru_loss, gru_accuracy = gru_model.evaluate(
    X_test,
    y_test,
    verbose = 0
)

print(f"GRU Loss: {gru_loss:.4f}")
print(f"GRU Accuracy : {gru_accuracy:.4f}")

GRU Loss: 0.7089
GRU Accuracy : 0.0000


In [30]:
print('Model Cpmparision')
print(f'LSTM Loss: {lstm_loss: .4f}')
print(f'LSTM Accuracy: {lstm_accuracy :.4f}')
print(f'GRU Loss: {gru_loss :.4f}')
print(f'GRU Accuracy: {gru_accuracy :.4f}')

Model Cpmparision
LSTM Loss:  0.7136
LSTM Accuracy: 0.0000
GRU Loss: 0.7089
GRU Accuracy: 0.0000


In [33]:
def predict_sentiment(model, text):
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen = max_length)
    prediction = model.predict(padded, verbose = 0)[0][0]

    if prediction >= 0.5:
        return "Positive" , prediction
    else:
        return "Negative" , prediction

In [44]:
text1 = "I Love Killing People"
result1, score1  = predict_sentiment(
    lstm_model,
    text1
)
print("LSTM Prediction :", result1, score1)

LSTM Prediction : Negative 0.49877504


In [45]:
result1, score1 = predict_sentiment(
    gru_model,
    text1
)

print("GRU Prediction :", result1, score1)

GRU Prediction : Positive 0.50297856


In [46]:
text2 = "I Love Physics"
result3, score3  = predict_sentiment(
    lstm_model,
    text2
)
print("LSTM Prediction :", result3, score3)

LSTM Prediction : Negative 0.49877504


In [47]:
result4, score4 = predict_sentiment(
    gru_model,
    text2
)

print("GRU Prediction :", result4, score4)

GRU Prediction : Positive 0.50297856
